### ISSUE TITLE
README is needed

### ISSUE THREAD

**Issue by thyrlian** [plu/SearchPath#1]
No idea what the project is about - "finding a path to somewhere via AppleMap"?  :P

I found some hints from the screenshots :)

**Comment by plu** [comment]
Repo will be deleted shortly, was just to demonstrate a CocoaPods issue:

https://github.com/CocoaPods/CocoaPods/pull/5514#issuecomment-278546536

**Comment by thyrlian** [comment]
Aha, so disappointed ;)

**Comment by plu** [comment]
:)
